#pragma once
#include "CoreMinimal.h"
#include "EActionType.generated.h"

UENUM(BlueprintType)
enum class EActionType : uint8 {
    None,
    Building = 5,
    Placing,
    PlantingOrTrapping = 8,
    HarvestCrop,
    GatherResource = 12,
    Pickup,
    EquipWithAnimation,
    Attack = 16,
    Charge = 18,
    SyncBlocks = 20,
    Dying = 19,
    CheerTaunt = 22,
    TradepointHaggle = 25,
    Craft = 27,
    LazyAction,
    GatherHerbs,
    Takeoff,
    Landing,
    FinalStep,
    PickupOre,
    MeleeTrain,
    ArcherTrain,
    DrawBows,
    AimA,
    AimB,
    ReleaseBow,
    DieTrampled,
    MountAttack,
    MountDie,
    PeddlingStall,
    StopWalkDeprecated,
    ChargeDefense,
    RunStop,
    PushedBack,
    FinishingOff,
    CheerVictory,
    CrossArms,
    PlowManual,
    UseFurnace,
    Firefight,
    TorchAction,
    Pray,
    Dig,
    IdlePeddle,
    PlantTree = 59,
    Conversation,
    BeingPet,
    QueuedPickup,
    UnequipCart,
    ConstructionDigFlatten,
    ClimbLadderUp,
    ClimbLadderDown,
};

