#pragma once
#include "CoreMinimal.h"
#include "EBuildingType.generated.h"

UENUM()
enum class EBuildingType : uint32 {
    BurgagePlot_Lv1 = 3,
    LoggingCamp,
    Field,
    TradingPost,
    Mine_Lv1,
    BurgagePlot_Lv2,
    Pasture = 10,
    Marketplace = 13,
    HuntingCamp,
    Sawpit = 18,
    Windmill = 20,
    Well_Lv1,
    Smithy = 25,
    CommunalOven,
    Tannery = 28,
    HitchingPost = 30,
    SheepFarm,
    CharcoalKilns,
    Weaver,
    Church_Lv1,
    Quarry,
    Forager,
    Tavern_Lv1,
    FishingPond = 39,
    ArcheryRange,
    StoneGathererCamp = 42,
    Bloomery,
    TrainingCamp = 45,
    Tradepoint,
    Manor_Walls = 50,
    Apiary,
    Mine_Lv2,
    RallyPoint,
    Manor_Keep_Lv1 = 57,
    Manor_TaxOffice,
    FishermansHut,
    BurgagePlot_Lv3,
    Malthouse,
    MilitiaTrainingCamp,
    Granary_Lv2 = 68,
    Farmhouse,
    Storehouse_Lv1 = 72,
    BurgagePlotTool,
    LivestockMarket,
    Rubble,
    Willow,
    Church_Lv2,
    LivestockTradingPost = 79,
    Granary_Lv1,
    Manor_Palace_Lv3,
    Manor_Gatehouse_Lv3,
    Manor_Keep_Lv3,
    Shrine,
    Forester = 86,
    HomelessTents,
    Supplies,
    WoodcuttersLodge,
    FoodStall = 91,
    FirewoodStall,
    CommonGoodsStall,
    Manor_Gate_Lv1 = 95,
    Stable = 97,
    Manor_Palace_Lv1,
    Storehouse_Lv2,
    BanditCamp,
    FirewoodCart = 102,
    FoodCart,
    Scenario_DestroyedWindmill,
    Scenario_DestroyedGranary = 106,
    SettlerCampTool,
    ClayFurnace,
    EraseShrubsTool = 110,
    WorkerCamp,
    PackStation,
    CorpsePit,
    Well_Lv2,
    WoodenBridge,
    Tavern_Lv2,
    StonemasonCamp,
    LimeKiln,
    ConstructionYard,
    Manor_WoodenWallPiece = 470,
    Manor_WoodenPlatform,
    Manor_OuterTower_Lv1,
    Dyer,
    Manor_Palace_Lv2,
    Manor_Keep_Lv2,
    Manor_Wall_Stone_Small,
    Manor_Wall_Stone_Large,
    Manor_Gate_Lv2,
    Manor_OuterTower_Lv2,
    Manor_WoodenPlatformSupport,
    Manor_WoodenPlatformRailing,
    Manor_WoodenPlatformPlank,
    SiegeCamp,
    BurgagePlot_Lv4,
};

