#pragma once
#include "CoreMinimal.h"
#include "EItemType.generated.h"

UENUM()
enum class EItemType : uint32 {
    None,
    WheatGrain,
    StagCarcass,
    Hides,
    Leather,
    WheatFlour,
    Irontools,
    WoodenParts,
    Recipe_Clothes_Woolen,
    Pelts,
    Shoes,
    Flax,
    Cloth_Linen,
    Charcoal,
    IronOre,
    Rubble,
    Timber,
    planks,
    Herbs,
    fellingAxe = 20,
    huntingBow,
    Mallet,
    Wool,
    Saw,
    Knife,
    Sickle,
    RoughStone,
    Ale,
    Malt,
    fish,
    plow,
    Eel,
    RyeFlour,
    Recipe_Clothes_Linen,
    IronSlabs,
    deer_stag,
    chicken_body = 42,
    HareBody,
    HareCarcass,
    Pears,
    Quinces,
    body_male_lv1_variations = 52,
    Sheep = 72,
    body_female_lv1_variations = 89,
    headwear_female_lv1_variations = 93,
    Horse = 98,
    HorsewithCarriageReins = 108,
    bigCart,
    spears = 133,
    ShepherdsCrook = 136,
    HorseReins_Rider,
    Pickaxe,
    HideWashed,
    BeekeeperMask,
    Honey,
    Wax,
    Honeycomb,
    Robe,
    Salt,
    Clay,
    meat,
    Yarn,
    Clothes,
    Saddle,
    Candle = 153,
    BasketArmour,
    Warhorse = 156,
    Banner,
    gambesons = 163,
    mail_armor,
    Barley,
    Hops,
    Beer,
    RyeBread = 170,
    Berries,
    WheatBread,
    Pastries,
    Silk = 175,
    Spices,
    weapons_sidearms,
    weapons_polearms,
    hat_variations_lv2 = 204,
    warbows,
    crossbows,
    hood_up,
    bludgeon_2h_maul = 213,
    Firewood = 216,
    WheatSheaves,
    Handcart,
    Woad,
    Eggs,
    Milk,
    goat_body,
    shortAxe,
    work_hoe,
    work_flail,
    work_rollingPin,
    work_woodenSpade,
    water,
    empty_bucket,
    vegetables,
    empty_bag,
    body_lamb,
    corpse,
    oxBody,
    oxwhip = 236,
    debranching_target,
    hat_variations = 246,
    scabbard,
    retinue_polearms = 250,
    embeded_arrow = 252,
    tradingWagon = 254,
    Brushwood,
    backpack,
    smallLog,
    CONSUM_ale,
    mug,
    distaff,
    slag,
    body_male_smith,
    hammer,
    iron_rod,
    basket = 267,
    Fieldstone_DEPREC,
    clayTILES,
    shields_small,
    shields_large,
    militia_helmets_resource = 273,
    townguard_weapon,
    helmets_retinue_tier1 = 276,
    archer_sidearm,
    retinue_sidearms,
    mushrooms,
    accessories_civilian_lv1_hoodDown,
    heads_male_variations,
    hair_male_variations,
    DressedStone,
    handcart_axel,
    helmets_militia_tier0,
    heads_female_variations,
    hound_body,
    mercenary_helmet_poor,
    mercenary_helmet_medium,
    shields_retinue_small,
    arrow,
    retinue_hats,
    PlateArmor,
    helmets_retinue_tier3,
    plow_axel,
    apples,
    empty_stone_basket,
    RyeSheaves,
    RyeGrain,
    dung,
    fertilizer,
    dyes,
    horse_harness_wagon,
    body_male_lv2_variations,
    horse_cart_axel,
    mule,
    head_male_chubby,
    body_male_lv1_chubby,
    head_female_chubby,
    body_female_lv1_chubby,
    body_male_variations_combat,
    banner_carrier_sword,
    stirring_stick,
    crossbow_bolt,
    fishingRod,
    fishingFish,
    iron_parts,
    hunting_limit,
    fishing_limit,
    sausage,
    pig_body,
    siege_ladders,
    smokedfish,
    zweiback,
    mead,
    lebkuchen,
    cider,
    chisel,
    Mortar,
    SmallGame,
    Venison,
    Mutton,
    Chevon,
    Pork,
    Beef,
    Chicken,
    Carrots,
    Cabbages,
    Beetroots,
    VirtualRequirementItem_Faith_Lv1,
    VirtualRequirementItem_Faith_Lv2,
    VirtualRequirementItem_Faith_Lv3,
    VirtualRequirementItem_Faith_Lv4,
};

