#pragma once
#include "CoreMinimal.h"
#include "EJobType.generated.h"

UENUM(BlueprintType)
enum class EJobType : uint8 {
    Woodcutter = 1,
    Builder,
    Hunter,
    Miller = 8,
    Tanner,
    Tailor,
    Cobbler,
    SheepHerder,
    CharcoalBurner,
    Weaver,
    Miner,
    Blacksmith,
    Sawyer,
    Forager,
    Joiner = 20,
    Brewer = 22,
    StoneGatherer,
    Bloomer,
    TravellingMerchant_FreeMerchant = 27,
    Butcher = 29,
    MalthouseWorker = 33,
    Cooper = 37,
    Baker,
    SaltHouseWorker = 40,
    Thresher,
    Farmer,
    LarderWorker,
    GranaryWorker,
    WarehouseWorker,
    FreeLivestockMerchant,
    TaxCollector,
    Trader,
    LivestockTraderPassive,
    Forester,
    OxHandler,
    FirewoodCutter,
    TavernKeeper,
    LivestockBringer = 55,
    Armorer,
    Bowyer,
    SoonToBeBandit,
    Guard,
    Servant,
    Tilemaker,
    RetinueMember_UI_only,
    Dyer,
    PackStationWorker,
    Gravedigger,
    Fisherman,
    QuarryWorker,
    Stonemason,
    LimeKilnWorker,
    Smallholder,
};

