#pragma once
#include "CoreMinimal.h"
#include "EProblem.generated.h"

UENUM(BlueprintType)
enum class EProblem : uint8 {
    Hunger,
    Cold,
    Jobless,
    NoWorkersEmployed,
    NeedsStorage,
    CropNotChosen,
    NoAssignment,
    WoodenPartsLowQuality,
    Sickness,
    Death,
    IronToolsLow,
    IronToolsBroken,
    NoGoodChosenForSale,
    NoPastureSpace,
    NothingToPlough,
    CantAffordProduce,
    NotEnoughTradeRoutes,
    CantFindStockForSelling,
    Homelessness,
    SpoilingFood,
    CanUpgrade,
    OccasionalNeeds,
    NoSupplies,
    NotEnoughTreasuryToPayTheRoyalTax,
    NoWaterAccess,
    NoSuperfarm,
    NoFields,
    ExtensionsAvailable,
    CantFindResourceToHarvest,
    RoadNotConnected,
    MarketSquareNotConnected,
    OutOfStorageSpace,
    OutOfPantrySpace,
    ExposedStorage,
    ExposedFood,
    OxNoGuide,
    NoGatehouse,
    NoShelter,
    LowApproval,
    RequirementsCausingApprovalLoss,
    NoBuilders,
    NoFreeOxen,
    BadLogistics,
    NoTools,
    NoClothes,
    NoCloaks,
    NoShoes,
    Unburied,
    TransportLimitReached,
    ConstructionResourcesMissing,
    Unmaintained,
};

