#pragma once
#include "CoreMinimal.h"
#include "ETaskType.generated.h"

UENUM(BlueprintType)
enum class ETaskType : uint8 {
    None,
    Construction,
    ConstructionGathering,
    TreeChopping,
    BringItemToBuilding,
    GetPlough,
    ReturnToFarm,
    GetAnimal,
    OxPlowing = 10,
    Sowing,
    HarvestingGrain,
    GoingHomeToEat,
    GoingHomeToWarmUp,
    GoingToTheMarket,
    MerchantGoingToBuyGoods,
    GoToLocation,
    Hunting,
    Delaying,
    GetResourceFromOtherUnit,
    MovingItemBetweenBuilding = 22,
    Gathering,
    Attacking,
    Crafting,
    SellAtStall,
    Mine,
    LoadResourceOntoUnit,
    Assemble,
    Lazy,
    GatherHerbs,
    PickupOre,
    Trade,
    TrainingMelee,
    TrainingArchery,
    FireAtWill,
    Volley,
    Retreat,
    Flee,
    BringUnit,
    Follow,
    BuyAtTradepoint,
    SetupStall,
    MerchantBuy,
    FinishOff,
    PloughManual,
    DropResource,
    UseFurnace,
    Firefight,
    GoEquip,
    TorchBuilding,
    Pray,
    Garrison,
    Ungarrison,
    Rally,
    PlantOrTrap,
    PlantTree,
    GrabLootOrDismantle,
    MountHorse,
    CollectStock,
    TradeStock,
    FlattenGround,
    MuleTrade_Interregion,
    MakeFollow,
    DeepMine,
};

