#pragma once
#include "CoreMinimal.h"
#include "EUpgradeType.generated.h"

UENUM()
enum class EUpgradeType : uint32 {
    None,
    BurgagePlot_Lv2 = 2,
    BurgagePlot_Lv3 = 4,
    BurgagePlot_Lv4,
    Church_Lv2,
    Storehouse_Lv2,
    Granary_Lv2,
    TradeWagon = 10,
    PloughingStation,
    BurgageExpansion,
    OrderOxen,
    Stable,
    HerbGarden,
    Rebuild,
    FenceUp,
    DeepMine,
    OrderHorse,
    upg_to_work_camp,
    OrderMule,
    Well_Lv2,
    Tavern_Lv2,
    Smallholding,
    SmokingShed,
    OrderHuntingHound,
    OrderPig,
    OrderGoat,
    PlantBeetroots,
    PlantCarrots,
    PlantCabbages,
    PlantQuinces,
    PlantApples,
    PlantPears,
    Clutter = 100,
    ChickenCoop,
    AnimalPen,
    Blacksmith,
    Bakery,
    Brewery,
    Tailor,
    Cobbler,
    VegetableGarden,
    Joiner,
    Armorer,
    Bowyer,
    Orchard,
    Butcher,
    Apiary,
    Count,
};

